spring.application.name=api-gateway
server.port=8080
server.max-http-request-header-size=65536
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.registry-fetch-interval-seconds=2
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10
spring.cloud.loadbalancer.cache.enabled=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER:https://accepted-skylark-8794.clerk.accounts.dev}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URL:https://accepted-skylark-8794.clerk.accounts.dev/.well-known/jwks.json}
bideasy.cors-origin=${CORS_ORIGIN:http://localhost:3000}
